### ISSUE TITLE
canCreate

### ISSUE THREAD

**Issue by Gustyne** [DarkIsDude/DataTable#1]
Salut ! Je suis étudiante en GIS et un prof m'a parlé de ton code. Je l'utilise pour un stage, il est vraiment top ! 
J'ai juste un petit problème : je gère des droits d'accès/d'actions et je n'arrive pas à donner seulement le droit d'ajouter (avec le droit de voir). 
Pourtant, j'écris bien  : $table->canCreate(true);  mais l'icône ne s'affiche pas sur ma page... 

Comment je peux faire? merci d'avance ! 
Justine

**Comment by Gustyne** [comment]
c'est bon j'ai trouvé !

$table->can(true);
$table->canDelete(false);

**Comment by DarkIsDude** [comment]
Courage alors 👍 , content que le projet soit utilisé, ça m'a bien fait rire 😉

**Comment by Gustyne** [comment]
Ca fait deja 2 fois que j'ai l'occasion de l'utiliser, t'imagines pas comme
c'est pratique !!! Merci a toi ;)

On 9 Jul 2018 15:30, "Edouard COMTET" <notifications@github.com> wrote:

Courage alors 👍 , content que le projet soit utilisé, ça m'a bien fait
rire 😉

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/DarkIsDude/DataTable/issues/1#issuecomment-403479760>,
or mute the thread
